package br.com.javahome.views;

import br.com.javahome.ApplicationContext;
import br.com.javahome.event.EventBus;
import br.com.javahome.model.ConsumeValue;
import br.com.javahome.model.Outlet;
import br.com.javahome.model.RoomData;
import br.com.javahome.ui.ChartPanelUI;
import br.com.javahome.ui.ComboBoxUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import static br.com.javahome.event.EventType.ROOM_DATA_FETCH;
import static java.awt.Color.BLACK;

public class ElectricalView {
    private JPanel rootPanel;
    private JLabel name;
    private JLabel type;
    private JLabel status;
    private JLabel powerUsage;
    private JPanel chart;
    private JComboBox<String> sensors;
    private ChartPanel chartPanel1;


    private final NumberFormat numberFormat;
    private final List<Outlet> outlets = new ArrayList<>();
    private final DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    public ElectricalView(final EventBus eventBus, final NumberFormat numberFormat) {
        this.numberFormat = numberFormat;
        $$$setupUI$$$();
        eventBus.subscribe(ROOM_DATA_FETCH, this::receive);
    }

    private void receive(RoomData data) {
        outlets.clear();
        outlets.addAll(data.outlets());
        SwingUtilities.invokeLater(() -> {
            sensors.removeAllItems();
            outlets.forEach(it -> sensors.addItem(it.id()));
        });
    }

    private void createDataset(List<ConsumeValue> consumeValueList) {
        dataset.clear();
        consumeValueList.forEach(it -> dataset.addValue(it.value(), "", it.time()));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        rootPanel.setBackground(new Color(-16777216));
        rootPanel.setMinimumSize(new Dimension(310, 380));
        rootPanel.setPreferredSize(new Dimension(290, 290));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16742905));
        label1.setHorizontalAlignment(0);
        label1.setPreferredSize(new Dimension(290, 30));
        label1.setText("Tomada Elétrica");
        rootPanel.add(label1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setBackground(new Color(-16777216));
        panel1.setMinimumSize(new Dimension(290, 375));
        panel1.setOpaque(false);
        panel1.setPreferredSize(new Dimension(290, 160));
        rootPanel.add(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Informações Gerais", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(10, 0, 0, 0), 5, 1, true, false));
        panel2.setAutoscrolls(true);
        panel2.setBackground(new Color(-12828863));
        panel2.setForeground(new Color(-16777216));
        panel2.setMinimumSize(new Dimension(-1, -1));
        panel2.setOpaque(false);
        panel2.setPreferredSize(new Dimension(105, 120));
        panel2.setRequestFocusEnabled(false);
        panel2.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(panel2);
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-12828863));
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-16751353));
        label2.setText("ID:");
        label2.setVisible(true);
        panel2.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-16751353));
        label3.setText("Nome:");
        panel2.add(label3, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-16751353));
        label4.setText("Tipo");
        panel2.add(label4, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-16751353));
        label5.setText("Situação:");
        panel2.add(label5, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$(null, Font.BOLD, -1, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setForeground(new Color(-16751353));
        label6.setText("Consumo Atual:");
        panel2.add(label6, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 5, 0, 0), 5, 1));
        panel3.setAutoscrolls(false);
        panel3.setBackground(new Color(-12828863));
        panel3.setForeground(new Color(-16777216));
        panel3.setMinimumSize(new Dimension(145, 68));
        panel3.setOpaque(false);
        panel3.setPreferredSize(new Dimension(155, 120));
        panel3.putClientProperty("html.disable", Boolean.TRUE);
        panel1.add(panel3);
        name = new JLabel();
        Font nameFont = this.$$$getFont$$$(null, -1, -1, name.getFont());
        if (nameFont != null) name.setFont(nameFont);
        name.setForeground(new Color(-16751353));
        name.setText("-");
        panel3.add(name, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        type = new JLabel();
        Font typeFont = this.$$$getFont$$$(null, -1, -1, type.getFont());
        if (typeFont != null) type.setFont(typeFont);
        type.setForeground(new Color(-16751353));
        type.setHorizontalTextPosition(11);
        type.setText("-");
        panel3.add(type, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        status = new JLabel();
        Font statusFont = this.$$$getFont$$$(null, Font.BOLD, -1, status.getFont());
        if (statusFont != null) status.setFont(statusFont);
        status.setForeground(new Color(-16751353));
        status.setText("-");
        panel3.add(status, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        powerUsage = new JLabel();
        powerUsage.setForeground(new Color(-16751353));
        powerUsage.setText("-");
        panel3.add(powerUsage, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel3.add(sensors, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chart = new JPanel();
        chart.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        chart.setMinimumSize(new Dimension(190, 72));
        chart.setOpaque(false);
        chart.setPreferredSize(new Dimension(290, 160));
        rootPanel.add(chart);
        chart.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Histórico de Consumo", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        chartPanel1.setPreferredSize(new Dimension(280, 129));
        chart.add(chartPanel1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        sensors = new ComboBoxUI();

        sensors.addItemListener(e -> {
            outlets.stream().filter(it -> {
                String item = (String) e.getItem();
                return it.id().equalsIgnoreCase(item);
            }).findFirst().ifPresent(this::updateLabels);
        });

        JFreeChart lineChart = ChartFactory.createLineChart(
                ApplicationContext.getProperty("app.chart.outlet.title"),
                ApplicationContext.getProperty("app.chart.outlet.x-axis"),
                ApplicationContext.getProperty("app.chart.outlet.y-axis"),
                dataset,
                PlotOrientation.VERTICAL,
                false, false, false);

        chartPanel1 = new ChartPanelUI(lineChart);
        chartPanel1.setBackground(BLACK);
    }

    private void updateLabels(final Outlet outlet) {
        name.setText(outlet.name());
        type.setText(ApplicationContext.getProperty(outlet.type().property()).toUpperCase());
        powerUsage.setText(numberFormat.format(outlet.powerUsage()) + " Kw/h");
        status.setText(ApplicationContext.getProperty(outlet.inUse() ? "app.messages.busy" : "app.messages.available"));
        createDataset(outlet.historyConsume());
    }

}
