package br.com.javahome.views;

import br.com.javahome.ApplicationContext;
import br.com.javahome.event.EventBus;
import br.com.javahome.model.ConsumeValue;
import br.com.javahome.model.Light;
import br.com.javahome.model.RoomData;
import br.com.javahome.ui.ChartPanelUI;
import br.com.javahome.ui.SliderUI;
import br.com.javahome.ui.TabbedPaneUI;
import br.com.javahome.ui.ToggleButtonUI;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

import static br.com.javahome.event.EventType.ROOM_DATA_FETCH;
import static java.awt.Color.BLACK;

public class LightView {
    private JLabel id;
    private JLabel name;
    private JLabel brightness;
    private JLabel status;
    private JLabel lastChanged;
    private JPanel rootPanel;
    private JTabbedPane tabbedPane1;
    private JPanel form;
    private JPanel chart;
    private JToggleButton toggleButton1;
    private JSlider slider1;
    private ChartPanel chartPanel1;

    private final ImageIcon ICON_OK;
    private final ImageIcon ICON_NOK;
    private final NumberFormat numberFormat;
    private final DateTimeFormatter dateTimeFormatter;
    private final DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    public LightView(final EventBus eventBus, final NumberFormat numberFormat, final DateTimeFormatter dateTimeFormatter) {
        $$$setupUI$$$();
        this.numberFormat = numberFormat;
        this.dateTimeFormatter = dateTimeFormatter;
        ICON_OK = new ImageIcon(Objects.requireNonNull(getClass().getResource("/icons/ok.png"), "Icon /icons/ok.png not found"));
        ICON_NOK = new ImageIcon(Objects.requireNonNull(getClass().getResource("/icons/error.png"), "Icon /icons/error.png not found"));
        eventBus.subscribe(ROOM_DATA_FETCH, this::receive);
    }

    private void receive(RoomData data) {
        Light light = data.light();
        id.setText(light.id().toUpperCase());
        name.setText(light.name());
        brightness.setText("%s%%".formatted(numberFormat.format(light.brightness())));
        lastChanged.setText(dateTimeFormatter.format(light.lastChanged()));
        setStatus(light.state());
        createDataset(light.historyConsume());
    }

    public void setStatus(boolean state) {
        status.setIcon(state ? ICON_OK : ICON_NOK);
        status.setText(ApplicationContext.getProperty(state ? "app.messages.on" : "app.messages.off"));
    }

    private void createDataset(List<ConsumeValue> consumeValueList) {
        dataset.clear();
        consumeValueList.forEach(it -> dataset.addValue(it.value(), "", it.time()));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        rootPanel.setBackground(new Color(-16777216));
        rootPanel.setMinimumSize(new Dimension(290, 290));
        rootPanel.setPreferredSize(new Dimension(290, 290));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16742905));
        label1.setHorizontalAlignment(0);
        label1.setPreferredSize(new Dimension(290, 30));
        label1.setText("Iluminação");
        rootPanel.add(label1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setBackground(new Color(-16777216));
        panel1.setMinimumSize(new Dimension(290, 375));
        panel1.setOpaque(false);
        panel1.setPreferredSize(new Dimension(290, 160));
        rootPanel.add(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Informações Gerais", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), 5, 1));
        panel2.setAutoscrolls(true);
        panel2.setBackground(new Color(-12828863));
        panel2.setForeground(new Color(-16777216));
        panel2.setMinimumSize(new Dimension(-1, -1));
        panel2.setOpaque(false);
        panel2.setPreferredSize(new Dimension(105, 120));
        panel2.setRequestFocusEnabled(false);
        panel2.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(panel2);
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-12828863));
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-16751353));
        label2.setText("ID:");
        label2.setVisible(true);
        panel2.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-16751353));
        label3.setText("Nome:");
        panel2.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-16751353));
        label4.setText("Brilho:");
        panel2.add(label4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-16751353));
        label5.setText("Situação:");
        panel2.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$(null, Font.BOLD, -1, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setForeground(new Color(-16751353));
        label6.setText("Instalada em:");
        panel2.add(label6, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(5, 1, new Insets(0, 5, 0, 0), 5, 1));
        panel3.setAutoscrolls(false);
        panel3.setBackground(new Color(-12828863));
        panel3.setForeground(new Color(-16777216));
        panel3.setMinimumSize(new Dimension(145, 68));
        panel3.setOpaque(false);
        panel3.setPreferredSize(new Dimension(165, 120));
        panel3.putClientProperty("html.disable", Boolean.TRUE);
        panel1.add(panel3);
        id = new JLabel();
        id.setBackground(new Color(-12828863));
        Font idFont = this.$$$getFont$$$(null, -1, -1, id.getFont());
        if (idFont != null) id.setFont(idFont);
        id.setForeground(new Color(-16751353));
        id.setText("-");
        panel3.add(id, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        name = new JLabel();
        Font nameFont = this.$$$getFont$$$(null, -1, -1, name.getFont());
        if (nameFont != null) name.setFont(nameFont);
        name.setForeground(new Color(-16751353));
        name.setText("-");
        panel3.add(name, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        brightness = new JLabel();
        Font brightnessFont = this.$$$getFont$$$(null, -1, -1, brightness.getFont());
        if (brightnessFont != null) brightness.setFont(brightnessFont);
        brightness.setForeground(new Color(-16751353));
        brightness.setHorizontalTextPosition(11);
        brightness.setText("-");
        panel3.add(brightness, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        status = new JLabel();
        status.setForeground(new Color(-16751353));
        status.setText("-");
        panel3.add(status, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lastChanged = new JLabel();
        lastChanged.setForeground(new Color(-16751353));
        lastChanged.setText("-");
        panel3.add(lastChanged, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tabbedPane1.setBackground(new Color(-16777216));
        tabbedPane1.setDoubleBuffered(false);
        tabbedPane1.setEnabled(true);
        tabbedPane1.setFocusTraversalPolicyProvider(false);
        tabbedPane1.setFocusable(true);
        Font tabbedPane1Font = this.$$$getFont$$$(null, Font.BOLD, -1, tabbedPane1.getFont());
        if (tabbedPane1Font != null) tabbedPane1.setFont(tabbedPane1Font);
        tabbedPane1.setForeground(new Color(-16751353));
        tabbedPane1.setInheritsPopupMenu(false);
        tabbedPane1.setOpaque(false);
        tabbedPane1.setPreferredSize(new Dimension(290, 160));
        tabbedPane1.setTabPlacement(1);
        tabbedPane1.setVisible(true);
        rootPanel.add(tabbedPane1);
        form = new JPanel();
        form.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        form.setBackground(new Color(-16777216));
        form.setOpaque(false);
        form.setPreferredSize(new Dimension(279, 125));
        tabbedPane1.addTab("Controles", form);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), 5, -1));
        panel4.setAutoscrolls(true);
        panel4.setBackground(new Color(-12828863));
        panel4.setForeground(new Color(-16777216));
        panel4.setMinimumSize(new Dimension(-1, -1));
        panel4.setOpaque(false);
        panel4.setPreferredSize(new Dimension(100, 120));
        panel4.setRequestFocusEnabled(false);
        panel4.putClientProperty("html.disable", Boolean.FALSE);
        form.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setBackground(new Color(-12828863));
        Font label7Font = this.$$$getFont$$$(null, Font.BOLD, -1, label7.getFont());
        if (label7Font != null) label7.setFont(label7Font);
        label7.setForeground(new Color(-16751353));
        label7.setText("Luz");
        label7.setVisible(true);
        panel4.add(label7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        Font label8Font = this.$$$getFont$$$(null, Font.BOLD, -1, label8.getFont());
        if (label8Font != null) label8.setFont(label8Font);
        label8.setForeground(new Color(-16751353));
        label8.setText("Brilho:");
        panel4.add(label8, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 18));
        panel5.setAutoscrolls(false);
        panel5.setBackground(new Color(-12501184));
        panel5.setForeground(new Color(-16777216));
        panel5.setMinimumSize(new Dimension(145, 68));
        panel5.setOpaque(false);
        panel5.setPreferredSize(new Dimension(165, 120));
        panel5.putClientProperty("html.disable", Boolean.TRUE);
        form.add(panel5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        toggleButton1.setEnabled(false);
        toggleButton1.setPreferredSize(new Dimension(75, 30));
        panel5.add(toggleButton1);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel6.setOpaque(false);
        panel6.setPreferredSize(new Dimension(160, 1));
        panel5.add(panel6);
        slider1.setAlignmentX(0.5f);
        slider1.setAlignmentY(0.5f);
        slider1.setAutoscrolls(false);
        slider1.setEnabled(false);
        slider1.setPreferredSize(new Dimension(160, 24));
        panel5.add(slider1);
        chart = new JPanel();
        chart.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        chart.setMinimumSize(new Dimension(179, 72));
        chart.setOpaque(false);
        chart.setPreferredSize(new Dimension(279, 125));
        tabbedPane1.addTab("Estatística", chart);
        chartPanel1.setPreferredSize(new Dimension(285, 120));
        chart.add(chartPanel1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        tabbedPane1 = new TabbedPaneUI();
        toggleButton1 = new ToggleButtonUI("Ligar");

        toggleButton1.addItemListener(e -> {
            int stateChange = e.getStateChange();

            if (stateChange == ItemEvent.SELECTED) {
                System.out.println();
                // TODO  fazer isso
            } else {
                System.out.println();
            }
        });

        slider1 = new SliderUI();
        slider1.setPreferredSize(new Dimension(150, 25));
        slider1.setOpaque(false);
        slider1.addChangeListener(e -> {
            // do nothing
        });

        JFreeChart lineChart = ChartFactory.createLineChart(
                ApplicationContext.getProperty("app.chart.light.title"),
                ApplicationContext.getProperty("app.chart.light.x-axis"),
                ApplicationContext.getProperty("app.chart.light.y-axis"),
                dataset,
                PlotOrientation.VERTICAL,
                false, false, false);

        chartPanel1 = new ChartPanelUI(lineChart);
        chartPanel1.setBackground(BLACK);
    }
}
