package br.com.javahome.views;


import br.com.javahome.ApplicationContext;
import br.com.javahome.di.Qualifier;
import br.com.javahome.enums.ViewType;
import br.com.javahome.event.EventBus;
import br.com.javahome.model.RoomData;
import br.com.javahome.ui.RoomUI;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.Locale;

import static br.com.javahome.event.EventType.ROOM_DATA_FETCH;
import static br.com.javahome.event.EventType.ROOM_SELECTED;
import static br.com.javahome.ui.RoomUI.DEFAULT;


public class RoomDetailView {

    private JPanel leftPanel;
    private JPanel rootPanel;
    private JLabel name;
    private JLabel totalArea;
    private JLabel outletAmount;
    private JLabel lightSwitchAmount;
    private JLabel doorSize;
    private JButton lightBtn;
    private JButton eletricalBtn;
    private JButton tempBtn;
    private JButton securityBtn;

    private RoomUI room;
    private final NumberFormat numberFormat;


    public RoomDetailView(@Qualifier("leftPanel") final JPanel leftPanel, final EventBus eventBus, NumberFormat numberFormat) {
        this.leftPanel = leftPanel;
        this.numberFormat = numberFormat;
        eventBus.subscribe(ROOM_SELECTED, room -> this.room = (RoomUI) room);
        eventBus.subscribe(ROOM_DATA_FETCH, this::receive);

        lightBtn.addMouseListener(createHoverListener());
        lightBtn.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, DEFAULT));
        eletricalBtn.addMouseListener(createHoverListener());
        eletricalBtn.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, DEFAULT));
        tempBtn.addMouseListener(createHoverListener());
        tempBtn.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 1, DEFAULT));
        securityBtn.addMouseListener(createHoverListener());
        securityBtn.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, DEFAULT));

        lightBtn.addActionListener(e -> {
            changeLayoutOptions(ViewType.LIGHT);
        });

        eletricalBtn.addActionListener(e -> {
            changeLayoutOptions(ViewType.ELECTRICAL);
        });

        tempBtn.addActionListener(e -> {
            changeLayoutOptions(ViewType.TEMPERATURE);
        });

        securityBtn.addActionListener(e -> {
            changeLayoutOptions(ViewType.SECURITY);
        });
    }

    private MouseAdapter createHoverListener() {
        return new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                JButton btn = (JButton) e.getComponent();
                btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                JButton btn = (JButton) e.getComponent();
                btn.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        };
    }

    private void changeLayoutOptions(final ViewType viewType) {
        Container parent = rootPanel.getParent();
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.show(parent, viewType.name());
        ApplicationContext.currentViewType = viewType;
    }

    private void receive(RoomData data) {
        name.setText(data.name());
        outletAmount.setText(String.valueOf(data.outlets().size()));
        totalArea.setText(numberFormat.format(data.totalArea()) + " m²");
        lightSwitchAmount.setText(data.lightSwitchAmount().toString());
        doorSize.setText(numberFormat.format(data.doorSize()) + " m²");
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        rootPanel.setBackground(new Color(-16777216));
        rootPanel.setForeground(new Color(-3355444));
        rootPanel.setMinimumSize(new Dimension(290, 99));
        rootPanel.setPreferredSize(new Dimension(-1, -1));
        rootPanel.setRequestFocusEnabled(false);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setBackground(new Color(-16777216));
        panel1.setMinimumSize(new Dimension(290, 175));
        panel1.setOpaque(false);
        panel1.setPreferredSize(new Dimension(290, 145));
        rootPanel.add(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Informações", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), 5, 1));
        panel2.setAutoscrolls(false);
        panel2.setBackground(new Color(-12828863));
        panel2.setForeground(new Color(-16777216));
        panel2.setMinimumSize(new Dimension(-1, -1));
        panel2.setOpaque(false);
        panel2.setPreferredSize(new Dimension(115, 115));
        panel2.setRequestFocusEnabled(false);
        panel2.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(panel2);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-12828863));
        Font label1Font = this.$$$getFont$$$(null, -1, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16751353));
        label1.setText("Nome:");
        label1.setVisible(true);
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, -1, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-16751353));
        label2.setText("Área Total:");
        panel2.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, -1, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-16751353));
        label3.setText("Qtd. Tomadas:");
        panel2.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setForeground(new Color(-16751353));
        label4.setText("Qtd. Interruptores:");
        panel2.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setForeground(new Color(-16751353));
        label5.setText("Tamanho Porta:");
        panel2.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(5, 1, new Insets(0, 5, 0, 0), 5, 1));
        panel3.setAutoscrolls(false);
        panel3.setBackground(new Color(-12828863));
        panel3.setForeground(new Color(-16777216));
        panel3.setMinimumSize(new Dimension(145, 68));
        panel3.setOpaque(false);
        panel3.setPreferredSize(new Dimension(145, 115));
        panel3.putClientProperty("html.disable", Boolean.TRUE);
        panel1.add(panel3);
        name = new JLabel();
        name.setBackground(new Color(-12828863));
        Font nameFont = this.$$$getFont$$$(null, -1, -1, name.getFont());
        if (nameFont != null) name.setFont(nameFont);
        name.setForeground(new Color(-16751353));
        name.setText("-");
        panel3.add(name, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        totalArea = new JLabel();
        Font totalAreaFont = this.$$$getFont$$$(null, -1, -1, totalArea.getFont());
        if (totalAreaFont != null) totalArea.setFont(totalAreaFont);
        totalArea.setForeground(new Color(-16751353));
        totalArea.setText("-");
        panel3.add(totalArea, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outletAmount = new JLabel();
        Font outletAmountFont = this.$$$getFont$$$(null, -1, -1, outletAmount.getFont());
        if (outletAmountFont != null) outletAmount.setFont(outletAmountFont);
        outletAmount.setForeground(new Color(-16751353));
        outletAmount.setText("-");
        panel3.add(outletAmount, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        lightSwitchAmount = new JLabel();
        lightSwitchAmount.setForeground(new Color(-16751353));
        lightSwitchAmount.setText("-");
        panel3.add(lightSwitchAmount, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        doorSize = new JLabel();
        doorSize.setForeground(new Color(-16751353));
        doorSize.setText("-");
        panel3.add(doorSize, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setMinimumSize(new Dimension(225, 200));
        panel4.setOpaque(false);
        panel4.setPreferredSize(new Dimension(290, 200));
        rootPanel.add(panel4);
        lightBtn = new JButton();
        lightBtn.setBackground(new Color(-16777216));
        lightBtn.setBorderPainted(true);
        lightBtn.setFocusPainted(false);
        Font lightBtnFont = this.$$$getFont$$$(null, Font.BOLD, -1, lightBtn.getFont());
        if (lightBtnFont != null) lightBtn.setFont(lightBtnFont);
        lightBtn.setForeground(new Color(-16751353));
        lightBtn.setHideActionText(true);
        lightBtn.setHorizontalAlignment(0);
        lightBtn.setHorizontalTextPosition(0);
        lightBtn.setIcon(new ImageIcon(getClass().getResource("/icons/Light/idea.png")));
        lightBtn.setIconTextGap(4);
        lightBtn.setInheritsPopupMenu(false);
        lightBtn.setLabel("Iluminação");
        lightBtn.setMaximumSize(new Dimension(90, 66));
        lightBtn.setMinimumSize(new Dimension(90, 66));
        lightBtn.setOpaque(false);
        lightBtn.setPreferredSize(new Dimension(90, 45));
        lightBtn.setRequestFocusEnabled(true);
        lightBtn.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/light/idea_hover.png")));
        lightBtn.setSelected(true);
        lightBtn.setText("Iluminação");
        lightBtn.setVerticalAlignment(0);
        lightBtn.setVerticalTextPosition(3);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.45;
        gbc.weighty = 0.45;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(lightBtn, gbc);
        eletricalBtn = new JButton();
        eletricalBtn.setBorderPainted(true);
        eletricalBtn.setFocusPainted(false);
        Font eletricalBtnFont = this.$$$getFont$$$(null, Font.BOLD, -1, eletricalBtn.getFont());
        if (eletricalBtnFont != null) eletricalBtn.setFont(eletricalBtnFont);
        eletricalBtn.setForeground(new Color(-16751353));
        eletricalBtn.setHorizontalTextPosition(0);
        eletricalBtn.setIcon(new ImageIcon(getClass().getResource("/icons/Eletric/storm.png")));
        eletricalBtn.setRolloverEnabled(true);
        eletricalBtn.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/Eletric/storm_hover.png")));
        eletricalBtn.setText("Elétrica");
        eletricalBtn.setVerticalAlignment(0);
        eletricalBtn.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.55;
        gbc.weighty = 0.55;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 5;
        panel4.add(eletricalBtn, gbc);
        tempBtn = new JButton();
        tempBtn.setBorderPainted(true);
        tempBtn.setFocusPainted(false);
        Font tempBtnFont = this.$$$getFont$$$(null, Font.BOLD, -1, tempBtn.getFont());
        if (tempBtnFont != null) tempBtn.setFont(tempBtnFont);
        tempBtn.setForeground(new Color(-16751353));
        tempBtn.setHorizontalTextPosition(0);
        tempBtn.setIcon(new ImageIcon(getClass().getResource("/icons/Temperature/hot.png")));
        tempBtn.setRolloverEnabled(true);
        tempBtn.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/Temperature/hot_hover.png")));
        tempBtn.setText("Temperatura");
        tempBtn.setVerticalAlignment(0);
        tempBtn.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.45;
        gbc.weighty = 0.45;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(tempBtn, gbc);
        securityBtn = new JButton();
        securityBtn.setBorderPainted(true);
        securityBtn.setFocusPainted(false);
        Font securityBtnFont = this.$$$getFont$$$(null, Font.BOLD, -1, securityBtn.getFont());
        if (securityBtnFont != null) securityBtn.setFont(securityBtnFont);
        securityBtn.setForeground(new Color(-16751353));
        securityBtn.setHorizontalTextPosition(0);
        securityBtn.setIcon(new ImageIcon(getClass().getResource("/icons/Security/security.png")));
        securityBtn.setRolloverEnabled(true);
        securityBtn.setRolloverIcon(new ImageIcon(getClass().getResource("/icons/Security/security_hover.png")));
        securityBtn.setText("Segurança");
        securityBtn.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.55;
        gbc.weighty = 0.55;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 5;
        panel4.add(securityBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }


}
