package br.com.javahome.views;

import br.com.javahome.ApplicationContext;
import br.com.javahome.event.EventBus;
import br.com.javahome.model.Device;
import br.com.javahome.model.RoomData;
import br.com.javahome.ui.ScrollPaneUI;
import br.com.javahome.ui.TableUI;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import static br.com.javahome.event.EventType.ROOM_DATA_FETCH;

public class SecurityView {
    private JPanel rootPanel;
    private JLabel name;
    private JLabel type;
    private JLabel status;
    private JLabel id;
    private JTable table1;
    private JScrollPane scrollPane1;

    private final NumberFormat numberFormat;
    private final List<Device> devices = new ArrayList<>();
    private final Object[] columns;

    public SecurityView(final EventBus eventBus, final NumberFormat numberFormat) {
        this.numberFormat = numberFormat;
        $$$setupUI$$$();
        eventBus.subscribe(ROOM_DATA_FETCH, this::receive);
        String headers = ApplicationContext.getProperty("app.security.table-headers");
        columns = headers.split(",");
    }

    private void receive(RoomData data) {
        devices.clear();
        devices.addAll(data.security());

        List<Object[]> list = devices.stream().map(it -> {
            var status = getStatus(it);
            return new Object[]{it.id(), it.name(), status.toUpperCase()};
        }).toList();
        DefaultTableModel model = new DefaultTableModel(list.toArray(new Object[0][]), columns);
        table1.setModel(model);
        devices.stream().findFirst().ifPresent(this::updateLabels);
    }

    private String getStatus(Device device) {
        return device.status() ? "online" : "offline";
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rootPanel.setBackground(new Color(-16777216));
        rootPanel.setMinimumSize(new Dimension(290, 10));
        rootPanel.setPreferredSize(new Dimension(290, 10));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16742905));
        label1.setHorizontalAlignment(0);
        label1.setPreferredSize(new Dimension(290, 30));
        label1.setText("Segurança");
        rootPanel.add(label1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setBackground(new Color(-16777216));
        panel1.setMinimumSize(new Dimension(290, 375));
        panel1.setOpaque(false);
        panel1.setPreferredSize(new Dimension(290, 160));
        rootPanel.add(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Dados do Dispositivo", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), 5, 10));
        panel2.setAutoscrolls(true);
        panel2.setBackground(new Color(-12828863));
        panel2.setForeground(new Color(-16777216));
        panel2.setMinimumSize(new Dimension(-1, -1));
        panel2.setOpaque(false);
        panel2.setPreferredSize(new Dimension(105, 120));
        panel2.setRequestFocusEnabled(false);
        panel2.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(panel2);
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-12828863));
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-16751353));
        label2.setText("ID:");
        label2.setVisible(true);
        panel2.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-16751353));
        label3.setText("Nome:");
        panel2.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-16751353));
        label4.setHorizontalAlignment(4);
        label4.setText("Tipo");
        label4.setVerticalTextPosition(0);
        panel2.add(label4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-16751353));
        label5.setText("Situação");
        panel2.add(label5, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(4, 1, new Insets(0, 5, 0, 0), 5, 4));
        panel3.setAutoscrolls(false);
        panel3.setBackground(new Color(-12828863));
        panel3.setForeground(new Color(-16777216));
        panel3.setMinimumSize(new Dimension(145, 68));
        panel3.setOpaque(false);
        panel3.setPreferredSize(new Dimension(155, 120));
        panel3.putClientProperty("html.disable", Boolean.TRUE);
        panel1.add(panel3);
        name = new JLabel();
        Font nameFont = this.$$$getFont$$$(null, -1, -1, name.getFont());
        if (nameFont != null) name.setFont(nameFont);
        name.setForeground(new Color(-16751353));
        name.setText("-");
        panel3.add(name, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        type = new JLabel();
        Font typeFont = this.$$$getFont$$$(null, -1, -1, type.getFont());
        if (typeFont != null) type.setFont(typeFont);
        type.setForeground(new Color(-16751353));
        type.setHorizontalTextPosition(11);
        type.setText("-");
        panel3.add(type, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        status = new JLabel();
        status.setForeground(new Color(-16751353));
        status.setText("-");
        panel3.add(status, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        id = new JLabel();
        id.setForeground(new Color(-16751353));
        id.setText("-");
        panel3.add(id, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane1.setOpaque(false);
        scrollPane1.setPreferredSize(new Dimension(290, 160));
        rootPanel.add(scrollPane1);
        table1.setMinimumSize(new Dimension(290, 32));
        table1.setOpaque(false);
        table1.setPreferredScrollableViewportSize(new Dimension(270, 160));
        scrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        scrollPane1 = new ScrollPaneUI(rootPanel);
        table1 = new TableUI();
        table1.getSelectionModel().addListSelectionListener(e -> {
            int selectedRow = table1.getSelectedRow();
            if (e.getValueIsAdjusting() && selectedRow != -1) {
                Device device = devices.get(selectedRow);
                updateLabels(device);
            }
        });
    }

    private void updateLabels(Device device) {
        id.setText(device.id());
        name.setText(device.name());
        type.setText(ApplicationContext.getProperty(device.type().property()));
        status.setText(getStatus(device).toUpperCase());
    }
}
