package br.com.javahome.views;

import br.com.javahome.ApplicationContext;
import br.com.javahome.event.EventBus;
import br.com.javahome.model.ConsumeValue;
import br.com.javahome.model.RoomData;
import br.com.javahome.model.Temperature;
import br.com.javahome.ui.ChartPanelUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;

import static br.com.javahome.event.EventType.ROOM_DATA_FETCH;
import static java.awt.Color.BLACK;

public class TemperatureView {
    private JLabel name;
    private JLabel temperature;
    private JLabel relativeHumidity;
    private JPanel chart;
    private JLabel id;
    private ChartPanel chartPanel1;
    private JPanel rootPanel;

    private final NumberFormat numberFormat;
    private final DefaultCategoryDataset dataset = new DefaultCategoryDataset();


    public TemperatureView(final EventBus eventBus, final NumberFormat numberFormat) {
        this.numberFormat = numberFormat;
        $$$setupUI$$$();
        eventBus.subscribe(ROOM_DATA_FETCH, this::receive);
    }

    private void receive(RoomData data) {
        Temperature tempData = data.temperature();
        id.setText(tempData.id());
        name.setText(tempData.name());
        temperature.setText(numberFormat.format(tempData.currentTemperature()) + " °C");
        relativeHumidity.setText(numberFormat.format(tempData.relativeHumidity()) + " %");
        createDataset(tempData.historyConsume());
    }

    private void createDataset(List<ConsumeValue> consumeValueList) {
        dataset.clear();
        consumeValueList.forEach(it -> dataset.addValue(it.value(), "", it.time()));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        rootPanel.setBackground(new Color(-16777216));
        rootPanel.setMaximumSize(new Dimension(290, 32767));
        rootPanel.setMinimumSize(new Dimension(290, 400));
        rootPanel.setPreferredSize(new Dimension(290, 290));
        rootPanel.setVisible(true);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16742905));
        label1.setHorizontalAlignment(0);
        label1.setPreferredSize(new Dimension(290, 30));
        label1.setText("Temperatura");
        rootPanel.add(label1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setBackground(new Color(-16777216));
        panel1.setMinimumSize(new Dimension(290, 375));
        panel1.setOpaque(false);
        panel1.setPreferredSize(new Dimension(290, 155));
        rootPanel.add(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Informações Gerais", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), 5, 10));
        panel2.setAutoscrolls(true);
        panel2.setBackground(new Color(-12828863));
        panel2.setForeground(new Color(-16777216));
        panel2.setMinimumSize(new Dimension(-1, -1));
        panel2.setOpaque(false);
        panel2.setPreferredSize(new Dimension(105, 120));
        panel2.setRequestFocusEnabled(false);
        panel2.putClientProperty("html.disable", Boolean.FALSE);
        panel1.add(panel2);
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-12828863));
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-16751353));
        label2.setText("ID:");
        label2.setVisible(true);
        panel2.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-16751353));
        label3.setText("Nome:");
        panel2.add(label3, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-16751353));
        label4.setHorizontalAlignment(4);
        label4.setText("Temp. Atual:");
        label4.setVerticalTextPosition(0);
        panel2.add(label4, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 12), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-16751353));
        label5.setText("Umid. Relativa:");
        panel2.add(label5, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 5, 0, 0), 5, 0, true, false));
        panel3.setAutoscrolls(false);
        panel3.setBackground(new Color(-12828863));
        panel3.setForeground(new Color(-16777216));
        panel3.setMinimumSize(new Dimension(145, 68));
        panel3.setOpaque(false);
        panel3.setPreferredSize(new Dimension(155, 120));
        panel3.putClientProperty("html.disable", Boolean.TRUE);
        panel1.add(panel3);
        name = new JLabel();
        Font nameFont = this.$$$getFont$$$(null, -1, -1, name.getFont());
        if (nameFont != null) name.setFont(nameFont);
        name.setForeground(new Color(-16751353));
        name.setText("-");
        panel3.add(name, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        temperature = new JLabel();
        Font temperatureFont = this.$$$getFont$$$(null, -1, -1, temperature.getFont());
        if (temperatureFont != null) temperature.setFont(temperatureFont);
        temperature.setForeground(new Color(-16751353));
        temperature.setHorizontalTextPosition(11);
        temperature.setText("-");
        panel3.add(temperature, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        relativeHumidity = new JLabel();
        relativeHumidity.setForeground(new Color(-16751353));
        relativeHumidity.setText("-");
        panel3.add(relativeHumidity, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        id = new JLabel();
        id.setForeground(new Color(-16751353));
        id.setText("-");
        panel3.add(id, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chart = new JPanel();
        chart.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        chart.setMinimumSize(new Dimension(190, 72));
        chart.setOpaque(false);
        chart.setPreferredSize(new Dimension(290, 160));
        rootPanel.add(chart);
        chart.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16751353)), "Histórico de Temperatura", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16751353)));
        chartPanel1.setPreferredSize(new Dimension(280, 129));
        chart.add(chartPanel1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        JFreeChart lineChart = ChartFactory.createLineChart(
                "",
                ApplicationContext.getProperty("app.chart.temperature.x-axis"),
                ApplicationContext.getProperty("app.chart.temperature.y-axis"),
                dataset,
                PlotOrientation.VERTICAL,
                false, false, false);

        chartPanel1 = new ChartPanelUI(lineChart);
        chartPanel1.setBackground(BLACK);
    }
}
