app.title = Java House - Release 1.0
app.footer = Visão Geral
#app.logging.level = DEBUG
app.resource.home.path=/home
app.resource.room.path=/room?id=%s


app.chart.light.title=Consumo de Luz
app.chart.light.x-axis=Mês
app.chart.light.y-axis=Kw/h


app.chart.outlet.title=Consumo Tomada Elétrica
app.chart.outlet.x-axis=Mês
app.chart.outlet.y-axis=Kw/h

app.chart.temperature.x-axis=°C
app.chart.temperature.y-axis=Hora

app.logging-pattern=%s %s [%s] --- [%-40s] [<%s>:%d]: 


main.menu.preview-btn=Voltar

websocket.uri=ws://localhost:8765
websocket.timeout=30
websocket.max-retry=3




app.messages.on=Ligado
app.messages.off=Desligado
app.messages.available=Disponível
app.messages.busy=Ocupado
app.messages.outlet.type.single=Simples
app.messages.outlet.type.double=Duplo
app.messages.device.type.presence=Presença
app.messages.device.type.magnetic=Magnetico
app.messages.device.type.default=Padrão
app.security.table-headers=ID,Nome,Situação
